name: baby_cry_detector
description: "AI-powered baby cry detection and classification mobile app."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Core ML inference
  tflite_flutter: ^0.11.0

  # Audio recording and processing
  record: ^6.1.1
  audioplayers: ^6.5.1
  permission_handler: ^12.0.1
  
  # File system and storage
  path_provider: ^2.1.1
  path: ^1.8.0
  
  # State management
  provider: ^6.1.1
  
  # UI components
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  lottie: ^3.3.0
  
  # Utils
  intl: ^0.20.2
  shared_preferences: ^2.2.2
  
  # Networking (for model updates)
  http: ^1.1.0
  dio: ^5.3.2
  
  # Charts and visualization
  fl_chart: ^1.1.1
  
  # Native features
  vibration: ^3.1.4
  flutter_local_notifications: ^19.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Assets for the app
  assets:
    - assets/models/
